### ISSUE TITLE
Very first example in the docs is not working DSSL2

### ISSUE THREAD

**Issue by stamourv** [tov/dssl2#24]
The very first DSSL2 code example in the docs (root insertion in a BST) refers to a number of undefined functions (e.g., `empty?`, `new_node`, `fix_size`).
So it's not actually a working example that someone could just copy and run.
That's not great for the first example someone sees...

Especially confusing is the use of `empty?`, which looks like a function that could plausibly be provided by the language. I just had a student assume (possibly based on that example) that DSSL2 provided an `empty?` function, which it does not.

**Comment by tov** [comment]
Resolved by 6fa4a5590fdf80806943d2034f4655e3b363d43a.
