### ISSUE TITLE
Dssl2 Installation Issues

### ISSUE THREAD

**Issue by markovejnovic** [tov/dssl2#27]
## raco pkg install dssl2

I've recently updated racket from 7.8.2 to 7.9.1 when updating my system.
Upon running any `dssl2` script, I get:
```
standard-module-name-resolver: collection not found
  for module path: dssl2/lang/reader
  collection: "dssl2/lang"
  in collection directories:
   /home/marko/.racket/7.9/collects
   /usr/share/racket/collects
   ... [161 additional linked and package directories]
```

I've tried running `raco pkg install dssl2`, which threw:
```
Resolving "dssl2" via https://download.racket-lang.org/releases/7.9/catalog/
raco pkg install: cannot find package on catalogs
  package: dssl2
```

`curl https://download.racket-lang.org/releases/7.9/catalog/` gives a `text/html` 404.

This might be a `racket` catalog issue, but I've skimmed their [package catalog on GitHub](https://github.com/racket/release-catalog) (not sure if this is the right place), without any results. I've tried running:
```bash
grep -r -i dssl2 .
grep -r -i "jesse\.tov" .
grep -r -i northwestern .
```
where `cwd` is the `master` branch of the release catalog, commit [adadb82](https://github.com/racket/release-catalog/commit/adadb8256a1c9fb9d18a014fca08843336a45996), with no matches.

## raco pkg install -t github tov/dssl2

`raco pkg install -t github tov/dssl2` and `raco pkg install https://github.com/tov/dssl2.git` also don't work, being unhappy with the `master` branch name change to `main`. The error thrown is:
```
Querying Git references for dssl2 at git://github.com/tov/dssl2
git: could not find requested reference
  reference: master
  repo: tov/dssl2
  context...:
   /usr/share/racket/collects/net/git-checkout.rkt:359:0: select-commits
   /usr/share/racket/collects/net/git-checkout.rkt:73:8
   /usr/share/racket/collects/net/git-checkout.rkt:54:2: retry-loop
   /usr/share/racket/collects/pkg/private/stage.rkt:59:2: lookup-normally
   /usr/share/racket/collects/pkg/private/stage.rkt:107:0: stage-package/info
   /usr/share/racket/collects/pkg/private/install.rkt:141:0: install-packages
   /usr/share/racket/collects/pkg/private/install.rkt:925:4
   /usr/share/racket/collects/racket/contract/private/arrow-val-first.rkt:555:3
   /usr/share/racket/collects/racket/file.rkt:437:8
   /usr/share/racket/collects/racket/file.rkt:426:0: call-with-file-lock
   /usr/share/racket/collects/pkg/main.rkt:216:16
   (submod "/usr/share/racket/collects/pkg/main.rkt" main): [running body]
   "/usr/share/racket/collects/raco/raco.rkt": [running body]
   "/usr/share/racket/collects/raco/main.rkt": [running body]
```

I did get things to work by manually cloning `dssl2` manually and manually installing it with `raco`, but, **more importantly** I checked whether DrRacket would install `dssl2` well (as most people wouldn't probably know how to manually clone repos and would just follow the guide off the `README`) and it didn't, throwing the same error.

I suggest leaving the `master` branch name as a secondary branch until `racket` fixes their `master`-referring code.

## Other info
```
Racket: 7.9.1
OS: Arch, latest
```

**Comment by stamourv** [comment]
Sorry, just noticed that now. That's been fixed a while back.
